# Generated by Django 2.2 on 2020-08-10 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='auth_code',
            new_name='access_code',
        ),
    ]
