# Generated by Django 2.2 on 2020-08-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20200810_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='access_code',
        ),
        migrations.AddField(
            model_name='order',
            name='access_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='total',
            field=models.FloatField(),
        ),
    ]
