# Generated by Django 2.2 on 2020-08-14 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20200811_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=20)),
                ('reference', models.CharField(max_length=40)),
                ('json_dump', models.TextField()),
                ('payment_gateway', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.PaymentDetails'),
        ),
    ]
