name: Django CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  AWS_DEFAULT_REGION: eu-west-2
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CONTAINER_IMAGE: django_pssapp:${{ github.sha }}


jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        echo "MODE=dev" >> ./pss_app/pss_app/.env
        cd pss_app
        python manage.py test
        cd ..

  build-and-deploy:
    needs: test
    name: Building and pushing image to AWS ECR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: kciter/aws-ecr-action@v1
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: 672773168952.dkr.ecr.eu-west-2.amazonaws.com/djangopssapp
          region: eu-west-2
          tags: latest,${{ github.sha }}
          create_repo: true

#      - name: Push
##        if: giihub.ref == 'refs/heads/develop'
#        run: |
#          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE
#
